# Generated by Django 5.1 on 2025-10-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del usuario', max_length=100)),
                ('email', models.EmailField(help_text='Correo electrónico del usuario (debe ser único)', max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono del usuario', max_length=15, null=True)),
                ('rol', models.CharField(choices=[('pasajero', 'Pasajero'), ('conductor', 'Conductor')], default='pasajero', help_text='Rol del usuario en la plataforma', max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de registro del usuario')),
            ],
        ),
    ]
